# Generated by Django 3.2.9 on 2021-12-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='возраст'),
            preserve_default=False,
        ),
    ]
