# Generated by Django 3.2.9 on 2022-01-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20220114_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=18, null=True, verbose_name='возраст'),
        ),
    ]
